services:
  postgres:
    image: postgres:17
    container_name: postgres
    hostname: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    networks:
      - private_network

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27018:27017
    restart: unless-stopped
    networks:
      - private_network

volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local

networks:
  private_network:
    driver: bridge